### ISSUE TITLE
似乎有些消息的event.message.sender为NoneType？

### ISSUE THREAD

**Issue by crazypeace** [Hootrix/keyword_alert_bot#32]
Unhandled exception on on_greeting
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/updates.py", line 467, in _dispatch_update
    await callback(event)
  File "/etc/keyword_alert_bot-master/main.py", line 67, in on_greeting
    sender_username = event.message.sender.username if event.message.sender.username is not None else ''
AttributeError: 'NoneType' object has no attribute 'username'

**Comment by Hootrix** [comment]
event.message.sender? 
不知道
