### ISSUE TITLE
[BUG] docker部署报错。

### ISSUE THREAD

**Issue by xspoco** [Hootrix/keyword_alert_bot#64]
```
root@debian:~/keyword_alert_bot# docker run -it --name keyword_alert_bot -v $(pwd)/config.yml:/app/config.yml   yha8897/keyword_alert_bot

Unexpected exception in the receive loop
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/connection.py", line 332, in _recv_loop
    data = await self._recv()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/connection.py", line 369, in _recv
    return await self._codec.read_packet(self._reader)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/tcpfull.py", line 25, in read_packet
    packet_len_seq = await reader.readexactly(8)  # 4 and 4
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
concurrent.futures._base.CancelledError
Unhandled error while receiving data
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 505, in _recv_loop
    body = await self._connection.recv()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/connection.py", line 301, in recv
    raise err
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/connection.py", line 332, in _recv_loop
    data = await self._recv()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/connection.py", line 369, in _recv
    return await self._codec.read_packet(self._reader)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/tcpfull.py", line 25, in read_packet
    packet_len_seq = await reader.readexactly(8)  # 4 and 4
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
concurrent.futures._base.CancelledError
Please enter the code you received: xxxx
Signed in successfully as  xxxx
Unexpected exception in the receive loop
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/connection.py", line 332, in _recv_loop
    data = await self._recv()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/connection.py", line 369, in _recv
    return await self._codec.read_packet(self._reader)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/tcpfull.py", line 25, in read_packet
    packet_len_seq = await reader.readexactly(8)  # 4 and 4
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
concurrent.futures._base.CancelledError
Unhandled error while receiving data
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 505, in _recv_loop
    body = await self._connection.recv()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/connection.py", line 301, in recv
    raise err
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/connection.py", line 332, in _recv_loop
    data = await self._recv()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/connection.py", line 369, in _recv
    return await self._codec.read_packet(self._reader)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/telethon/network/connection/tcpfull.py", line 25, in read_packet
    packet_len_seq = await reader.readexactly(8)  # 4 and 4
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
concurrent.futures._base.CancelledError
#################################################################
##                                                             
##                          ● success                        
##   🤖️Telegram keyword alert bot (Version: 20230520.91a4ca1)  
##                                                             
#################################################################
```

docker部署的时候报错，但是可以输入code 后把bot运气起来，有也可以用。。

**Comment by Hootrix** [comment]
concurrent.futures._base.CancelledError 这个报错是上有依赖的问题，初步怀疑是网络问题相关。运行看到success就成功了

**Comment by Hootrix** [comment]
可以忽略

**Comment by xspoco** [comment]
> 可以忽略

好的，只是有报错在那边看着有些难受  :sweat_smile:

**Comment by Hootrix** [comment]
建议试试最新版本镜像
