### ISSUE TITLE
[BUG]yml配置好后，python3 ./main.py 运行报错。

### ISSUE THREAD

**Issue by HandingTo1** [Hootrix/keyword_alert_bot#66]
报错内容如下：
>root@debian:~/keyword_alert_bot-master# python3 ./main.py
Traceback (most recent call last):
  File "./main.py", line 14, in <module>
    from logger import logger
  File "/root/keyword_alert_bot-master/logger.py", line 3, in <module>
    from  config import _current_path,config
  File "/root/keyword_alert_bot-master/config.py", line 9, in <module>
    config = yaml.load(_f.read(),Loader = yaml.SafeLoader)
  File "/usr/local/lib/python3.7/dist-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/usr/local/lib/python3.7/dist-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.7/dist-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/local/lib/python3.7/dist-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0088: special characters are not allowed
  in "<unicode string>", position 5

看之前的回答说是yml的问题，但是我用[yml验证器](https://www.yamllint.com/)显示yml文件是没问题的。

**Comment by Hootrix** [comment]
YAML文件中可能存在一些非打印字符，例如制表符或者其他的控制字符。你可以尝试使用一些文本处理工具来查看这些字符，如 cat -v filename

**Comment by Hootrix** [comment]
建议你提供脱敏的配置文件

**Comment by HandingTo1** [comment]
> YAML文件中可能存在一些非打印字符，例如制表符或其他的控制字符。你可以尝试使用一些文本处理工具来查看这些字符，如 cat -v 文件名

谢谢，同样的配置，我已经用docker运行成功了。
