### ISSUE TITLE
[BUG] bot cannot be started

### ISSUE THREAD

**Issue by fabianski7** [Hootrix/keyword_alert_bot#92]
I had some problems:

**1.** The script apparently can't find the sqlite file with my username section. Entering the path manually seems to have fixed the problem below. This happens even with docker.

```
Traceback (most recent call last):
  File "/home/archlinux/Git/keyword_alert_bot/./main.py", line 39, in <module>
    bot = TelegramClient(f'{tmp_path}/.{account["bot_name"]}', account['api_id'], account['api_hash'],proxy = proxy).start(bot_token=account['bot_token'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/Git/keyword_alert_bot/telegram/lib/python3.12/site-packages/telethon/client/telegrambaseclient.py", line 289, in __init__
    session = SQLiteSession(session)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/Git/keyword_alert_bot/telegram/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 47, in __init__
    c = self._cursor()
        ^^^^^^^^^^^^^^
  File "/home/archlinux/Git/keyword_alert_bot/telegram/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 242, in _cursor
    self._conn = sqlite3.connect(self.filename,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
```

**2.** After solving problem 1, the following error is displayed

```
Traceback (most recent call last):
  File "/home/archlinux/Git/keyword_alert_bot/./main.py", line 39, in <module>
    bot = TelegramClient('f4biano_tg_login', account['api_id'], account['api_hash'],proxy = proxy).start(bot_token=account['bot_token'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/Git/keyword_alert_bot/telegram/lib/python3.12/site-packages/telethon/client/auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/archlinux/Git/keyword_alert_bot/telegram/lib/python3.12/site-packages/telethon/client/auth.py", line 135, in _start
    await self.connect()
  File "/home/archlinux/Git/keyword_alert_bot/telegram/lib/python3.12/site-packages/telethon/client/telegrambaseclient.py", line 555, in connect
    self.session.auth_key = self._sender.auth_key
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/Git/keyword_alert_bot/telegram/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 180, in auth_key
    self._update_session_table()
  File "/home/archlinux/Git/keyword_alert_bot/telegram/lib/python3.12/site-packages/telethon/sessions/sqlite.py", line 194, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked
Task was destroyed but it is pending!
task: <Task pending name='Task-11' coro=<MTProtoSender._send_loop() running at /home/archlinux/Git/keyword_alert_bot/telegram/lib/python3.12/site-packages/telethon/network/mtprotosender.py:462> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-12' coro=<MTProtoSender._recv_loop() running at /home/archlinux/Git/keyword_alert_bot/telegram/lib/python3.12/site-packages/telethon/network/mtprotosender.py:505> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-9' coro=<Connection._send_loop() running at /home/archlinux/Git/keyword_alert_bot/telegram/lib/python3.12/site-packages/telethon/network/connection/connection.py:316> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-10' coro=<Connection._recv_loop() running at /home/archlinux/Git/keyword_alert_bot/telegram/lib/python3.12/site-packages/telethon/network/connection/connection.py:335> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Exception ignored in: <coroutine object Connection._recv_loop at 0x74e75201f140>
RuntimeError: coroutine ignored GeneratorExit
```

**3.** Several alerts are displayed in the terminal, I don't know if this has any major problems. But they only appear when run via docker.

```
/home/archlinux/Git/keyword_alert_bot/./main.py:344: SyntaxWarning: invalid escape sequence '\.'
  if regex.search('^t\.me/',url):
/home/archlinux/Git/keyword_alert_bot/./main.py:432: SyntaxWarning: invalid escape sequence '\+'
  if regex.search('^\+',c):# 邀请链接
/home/archlinux/Git/keyword_alert_bot/./main.py:600: SyntaxWarning: invalid escape sequence '\s'
  text = regex.sub('\s*,\s*',',',text) # 确保英文逗号间隔中间都没有空格  如 "https://t.me/xiaobaiup, https://t.me/com9ji"
/home/archlinux/Git/keyword_alert_bot/./main.py:601: SyntaxWarning: invalid escape sequence '\s'
  splitd = [i for i in regex.split('\s+',text) if i]# 删除空元素
/home/archlinux/Git/keyword_alert_bot/./main.py:603: SyntaxWarning: invalid escape sequence '\s'
  await event.respond('输入需要订阅的关键字,支持js正则语法：`/[\s\S]*/ig`\n\nInput the keyword that needs to subscribe, support JS regular syntax：`/[\s\S]*/ig`')
/home/archlinux/Git/keyword_alert_bot/./main.py:674: SyntaxWarning: invalid escape sequence '\s'
  text = regex.sub('\s*,\s*',',',text) # 确保英文逗号间隔中间都没有空格  如 "https://t.me/xiaobaiup, https://t.me/com9ji"
/home/archlinux/Git/keyword_alert_bot/./main.py:675: SyntaxWarning: invalid escape sequence '\s'
  splitd = [i for i in regex.split('\s+',text) if i]# 删除空元素
/home/archlinux/Git/keyword_alert_bot/./main.py:711: SyntaxWarning: invalid escape sequence '\s'
  text = regex.sub('\s*,\s*',',',text) # 确保英文逗号间隔中间都没有空格  如 "https://t.me/xiaobaiup, https://t.me/com9ji"
/home/archlinux/Git/keyword_alert_bot/./main.py:712: SyntaxWarning: invalid escape sequence '\s'
  splitd = [i for i in regex.split('\s+',text) if i]# 删除空元素
/home/archlinux/Git/keyword_alert_bot/./main.py:930: SyntaxWarning: invalid escape sequence '\s'
  text = regex.sub('\s*,\s*',',',text) # 确保英文逗号间隔中间都没有空格  如 "https://t.me/xiaobaiup, https://t.me/com9ji"
/home/archlinux/Git/keyword_alert_bot/./main.py:942: SyntaxWarning: invalid escape sequence '\s'
  splitd = [i for i in regex.split('\s+',full_command) if i]# 删除空元素
/home/archlinux/Git/keyword_alert_bot/./main.py:977: SyntaxWarning: invalid escape sequence '\s'
  splitd = [i for i in regex.split('\s+',full_command) if i]# 删除空元素
/home/archlinux/Git/keyword_alert_bot/db/utils.py:105: SyntaxWarning: invalid escape sequence '\w'
  find = re.search('no such column: (?:\w+\.)([a-z_0-9]+)$',_e)
```

**Comment by Hootrix** [comment]
Problem 2 looks like you are starting multiple processes to access the SQLite file. Make sure that only one service is started

Problem 3 is that python 3.12 has a stricter syntax for regularization.
